# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7269c6b02f72986120ef901e8b64d3d119e9f9aa380e889928b93854b34aa37769b2369abeb763fd4e1a2143cef3cbc0504b56498ec02895429562460275a68

test:
  secret_key_base: 92bbf8b4a01630f8187a72385d29057466edee3c18308ac351df089a55647a1a8db7894df38365ee03060e0536c79ecb785a61230de556b6e3b42294bab8b6b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
